language: python
python:
  - "3.8"  # Replace with your desired Python version
  - "3.9"
  - "3.10"

# Install dependencies
install:
  - pip install -r requirements.txt  # Ensure you have a requirements.txt file
  - pip install pytest  # Install pytest for running tests (optional, replace with your test framework)

# Run tests
script:
  - pytest  # Replace with your test command

# Cache pip to speed up builds
cache: pip

# Notify via email if build fails or passes
notifications:
  email:
    recipients:
      anguri2264@gmail.com  # Replace with your email
    on_success: always  # Options: [always|never|change]
    on_failure: always






arch:
  - arm64

env:
  - IMGNAME=bradmorg/ubuntu:dbot

services:
  - docker

before_install:
- docker image build -t ${IMGNAME} .

script:
#TravisCI seems to be coming in on undocumented IP addresses.
 - dig +short myip.opendns.com @resolver1.opendns.com


after_success:
- docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
- echo "${SSH_KEY}" |  base64 --decode > /tmp/ssh_rsa
- chmod 600 /tmp/ssh_rsa
- ssh -o "StrictHostKeyChecking no" pi@${IPADDR} -i /tmp/ssh_rsa "echo test > test.log"
- ssh -o "StrictHostKeyChecking no" pi@${IPADDR} -i /tmp/ssh_rsa "cd ${INSTALL_LOCATION} && git pull ${TRAVIS_BUILD_WEB_URL} && docker image build -t ${IMGNAME} ${INSTALL_LOCATION}/. && docker push $
