
language: python
python:
  - "3.8"

env:
  global:
    - BUILD_NAME="My CI Pipeline"
    - BUILD_ENV="production"

script:
  - echo "Building $BUILD_NAME for $BUILD_ENV environment"
  - python --version
